name: Format files

on:
  push:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Format
        working-directory: ${{github.workspace}}/build
        run: make format

      - name: Clean build folder
        run: rm -rf ${{github.workspace}}/build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[CI] format files'
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}