name: Memory usage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Memory usage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind

      - name: Configure CMake
        run: cmake -B ${{ steps.strings.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=Debug -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Debug

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: |
          cat ../examples/in/1.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/2.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/3.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/4.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/5.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/6.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/7.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/8.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/9.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/10.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/11.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/12.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/13.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2
          cat ../examples/in/14.sql | valgrind --tool=massif ./itmo_low_level_programming_lab2

